# what programming language
language: python
# version of python
python:
  - "3.9"

services:
  - docker

# before Scripts
before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
